function [R] = chapter6FirstPage()

R = [];  % In case the user closes the GUI.
S.fh = figure('units','pixels',...
              'position',[250 0 800 750],...
              'menubar','none',...
              'name','chapter 6',...              
              'numbertitle','off',...
              'Color',[0 0 0],...
              'resize','off');
S.ax0 = axes('Position', [-0.5 0 2 1]);
imshow('Creative-Cool-Background.jpg');
S.ed1 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[305 450 180 30],...
                'string','Enter Number Of Equations');
S.ax1 = axes('Position',[0.2 0.7 0.6 0.2]);
imshow('Chapter-6.png');
S.pb1 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[50 350 250 90],...
                'string','Cramer',...
                'callback',{@pb_call1});
S.pb2 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[50 250 250 90],...
                'string','Gausse Elimination',...
                'callback',{@pb_call2});
S.pb3 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[50 150 250 90],...
                'string','LU Doolittle',...
                'callback',{@pb_call3});
S.pb4 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[500 350 250 90],...
                'string','LU Cholesky',...
                'callback',{@pb_call4});
S.pb5 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[500 250 250 90],...
                'string','LU Crout',...
                'callback',{@pb_call5});
S.pb6 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[500 150 250 90],...
                'string','Jacobi',...
                'callback',{@pb_call6});
S.pb7 = uicontrol('style','pushbutton',...
                 'units','pix',...
                 'backgroundColor',[71/255 209/255 71/255],...
                'position',[275 50 250 90],...
                'string','Gauss Seidel',...
                'callback',{@pb_call7});
uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call1(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 1);
    end
    function [] = pb_call2(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 2);
    end
    function [] = pb_call3(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 3);
    end
    function [] = pb_call4(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 4);
    end
    function [] = pb_call5(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 5);
    end
    function [] = pb_call6(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 6);
    end
    function [] = pb_call7(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        Chapter6MatrixEntrance(numberOfPoints, 7);
    end
end


