function [R] = GUI_36()
R = [];  % In case the user closes the GUI.
S.fh = figure('units','pixels',...
              'position',[400 200 500 400],...
              'menubar','none',...
              'name','chapter 2 bisection',...              
              'numbertitle','off',...
              'resize','off');
S.ed1 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 300 180 40],...
                'string','');
S.ed2 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 250 180 40],...
                'string','');
S.ed3 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 200 180 40],...
                'string','');
S.tx1 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 290 180 40],...
                'string','Interval');
S.tx2 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 240 180 40],...
                'string','Function');
S.tx3 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 190 180 40],...
                'string','Iteration Or number of steps');
S.pb1 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[50 20 200 70],...
                'string','Calculate using iteration',...
                'callback',{@pb_call1});
S.pb2 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[250 20 200 70],...
                'string','Calculate using precision',...
                'callback',{@pb_call2});
uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call1(varargin)
    % Callback for the pushbutton.
            interval = str2num(get(S.ed1, 'string'));
    f = get(S.ed2, 'string');
    numberOfIteration = str2num(get(S.ed3, 'string'));
    c = bisectionWithNumberOfIteration(f, interval, numberOfIteration);
    
    f = figure('units','pixels',...
       'menubar','none',...
       'position',[750 510 200 100]); % Create a new GUI.
E = uicontrol('style','text',...
              'units','pixels',...
              'position',[10 20 180 60],...
              'string',c);
          
        
    end
    function [] = pb_call2(varargin)
    % Callback for the pushbutton.
    interval = str2num(get(S.ed1, 'string'));
    f = get(S.ed2, 'string');
    numberOfIteration = str2num(get(S.ed3, 'string'));
    c = bisectionWithPrecision(f, interval, numberOfIteration);
    
    f = figure('units','pixels',...
       'menubar','none',...
       'position',[750 510 200 100]); % Create a new GUI.
E = uicontrol('style','text',...
              'units','pixels',...
              'position',[10 20 180 60],...
              'string',c);
          
        
    end
end



