function [R] = GUI_36()
R = [];  % In case the user closes the GUI.
S.fh = figure('units','pixels',...
              'position',[500 300 300 150],...
              'menubar','none',...
              'name','chapter 2 generalized newton raphson',...              
              'numbertitle','off',...
              'resize','off');
S.ed1 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[150 90 100 40],...
                'string','');
S.tx1 = uicontrol('style','text',...
                 'units','pix',...
                'position',[50 75 90 40],...
                'string','number of points');
S.pb1 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[50 20 200 70],...
                'string','next',...
                'callback',{@pb_call1});
uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call1(varargin)
          close(gcbf);
          w = str2num(get(S.ed1, 'string'))
          newnewtongeneralized2(4);
    end
end



