function [R] = GUI_36()

R = [];  % In case the user closes the GUI.
S.fh = figure('units','pixels',...
              'position',[500 250 400 400],...
              'menubar','none',...
              'name','chapter 3',...              
              'numbertitle','off',...
              'resize','off');
S.ed1 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[180 100 180 30],...
                'string','');
S.tx1 = uicontrol('style','text',...
                 'units','pix',...
                'position',[0 95 180 30],...
                'string','number of points');
S.pb1 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[0 300 400 100],...
                'string','Interpolation',...
                'callback',{@pb_call1});
S.pb2 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[0 200 400 100],...
                'string','Curvefitting',...
                'callback',{@pb_call2});
uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call1(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        interpolationFirst(numberOfPoints);
    end
    function [] = pb_call2(varargin)
        numberOfPoints = str2num(get(S.ed1, 'string'));
        close(gcbf);
        curveFittingFirst(numberOfPoints);
    end
end


