function [R] = GUI_36()
R = [];  % In case the user closes the GUI.
S.fh = figure('units','pixels',...
              'position',[400 200 700 400],...
              'menubar','none',...
              'name','chapter 3 Simpson 1/3',...              
              'numbertitle','off',...
              'resize','off');
S.ed1 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 300 180 40],...
                'string','');
S.ed2 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 250 180 40],...
                'string','');
S.ed3 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 200 180 40],...
                'string','');
S.ed4 = uicontrol('style','edit',...
                 'units','pix',...
                'position',[250 150 180 40],...
                'string','');
S.tx1 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 290 180 40],...
                'string','Interval');
S.tx2 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 240 180 40],...
                'string','Function');
S.tx3 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 190 180 40],...
                'string','Iteration Or number of steps');
S.tx4 = uicontrol('style','text',...
                 'units','pix',...
                'position',[60 140 180 40],...
                'string','h');
img = imread('Creative-Cool-Background.jpg');
s = size(img);
S.tx5 = uicontrol('style','edit',...
                 'enable','inactive',...
                 'units','pix',...
                 'backgroundColor','[0.9 0.9 0.9]',...
                'position',[460 20 220 340]);
S.pb1 = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[50 20 400 70],...
                'string','Calculate',...
                'callback',{@pb_call1});
        
            
%         I = imread('Creative-Cool-Background.jpg');
%         h = imshow(I,[10 20]);
%         RI = imref2d(size(I));
%         RI.XWorldLimits = [0 3];
%         RI.YWorldLimits = [2 5];
%         imshow(I,RI);
        
        


uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call1(varargin)
    end
end



